// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbLAkqzI2jZzmCuTh8JU7v4fz-XELLqWs',
    appId: '1:981661878088:web:3381879d39e4fed5aa957d',
    messagingSenderId: '981661878088',
    projectId: 'chatii-app',
    authDomain: 'chatii-app.firebaseapp.com',
    storageBucket: 'chatii-app.appspot.com',
    measurementId: 'G-64NCBMVPKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkEy905vzcmHUZ_z8-_CZGBrMzmUOaeps',
    appId: '1:981661878088:android:3120f688d8c1c0c1aa957d',
    messagingSenderId: '981661878088',
    projectId: 'chatii-app',
    storageBucket: 'chatii-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8yz5r3eQC8Gd33yX1wLaEd0xaE0RW_u4',
    appId: '1:981661878088:ios:c2257129354ab2bfaa957d',
    messagingSenderId: '981661878088',
    projectId: 'chatii-app',
    storageBucket: 'chatii-app.appspot.com',
    iosBundleId: 'com.example.chatii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8yz5r3eQC8Gd33yX1wLaEd0xaE0RW_u4',
    appId: '1:981661878088:ios:f56b11521bec23deaa957d',
    messagingSenderId: '981661878088',
    projectId: 'chatii-app',
    storageBucket: 'chatii-app.appspot.com',
    iosBundleId: 'com.example.chatii.RunnerTests',
  );
}
